# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cl < Formula
  desc "A tiny personal command manager with an interactive picker"
  homepage "https://github.com/silviopola/cl"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silviopola/cl/releases/download/v1.3.0/cl_1.3.0_darwin_amd64.tar.gz"
      sha256 "f573ff8bf301a62189a065607b7058b056b3f1a53c4286aeeb25f984af22343e"

      define_method(:install) do
        bin.install "cl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silviopola/cl/releases/download/v1.3.0/cl_1.3.0_darwin_arm64.tar.gz"
      sha256 "0f64359146858c43046551e563afb615a3b6597930c8584da7b082322a92d154"

      define_method(:install) do
        bin.install "cl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silviopola/cl/releases/download/v1.3.0/cl_1.3.0_linux_amd64.tar.gz"
      sha256 "88064a56c79c6e198ae0f3e3950168ac58cbd394bf0de5dd604c88c4b0856701"
      define_method(:install) do
        bin.install "cl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silviopola/cl/releases/download/v1.3.0/cl_1.3.0_linux_arm64.tar.gz"
      sha256 "795fbd01a10cffc9f21651122cfcfce1075a6d08678f3bb105deb5ef6b599f38"
      define_method(:install) do
        bin.install "cl"
      end
    end
  end

  test do
    system "#{bin}/cl", "-v"
  end
end
