# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cl < Formula
  desc "A tiny personal command manager with an interactive picker"
  homepage "https://github.com/silviopola/cl"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silviopola/cl/releases/download/v1.1.0/cl_1.1.0_darwin_amd64.tar.gz"
      sha256 "cbeed650ba4e44c0a67d4e8d41392ebb0ab0efbf7eb734a0b5537faf69bc00dd"

      define_method(:install) do
        bin.install "cl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silviopola/cl/releases/download/v1.1.0/cl_1.1.0_darwin_arm64.tar.gz"
      sha256 "926c74d7c5798119e78bf46cf42157fa267a9de7fc1c12bf369a88887fe84972"

      define_method(:install) do
        bin.install "cl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silviopola/cl/releases/download/v1.1.0/cl_1.1.0_linux_amd64.tar.gz"
      sha256 "38758ec60ad39632f34ffb111dcd95d696996e507573cb339953e96192f2feea"
      define_method(:install) do
        bin.install "cl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silviopola/cl/releases/download/v1.1.0/cl_1.1.0_linux_arm64.tar.gz"
      sha256 "d500c7f1b7b29df5956c4baa11260af93e2b991b34e28123d7784907b3242961"
      define_method(:install) do
        bin.install "cl"
      end
    end
  end

  test do
    system "#{bin}/cl", "-v"
  end
end
